### ISSUE TITLE
See when the last manual watering event was performed

### ISSUE THREAD

**Issue by Circleview** [Circleview/nanismus#79]
**As Kirstin** 
**I want to** see when the last manual watering event was performed over the website
**to** guess when I need to perform the  next watering event. 

**AC**
I get a feeling of when I need to come back to the website to perform a new watering action. 

**UAT**
- [x] Show an icon to make clear that the following text will show the last watering action
- [x] Show more that just the timestamp of the last watering action. Make it more tangible for the use. Which means show words like "recently" or minutes, hours, days or so.

**Comment by Circleview** [comment]
**Tasks**
- [ ] Set up a feature toggle to enable the feature on test but not on production but do the integration test on the production page at the same time.
- [ ] Set up a sub php file to catch the latest timestamp of the manual watering event and post this timestamp flat on the index page. 
- [ ] Check how long the last watering event has been passed and distinguish between minutes, hours and days by displaying these timestamp values. 
- [ ] Embed an icon to make the last watering event visually obvious. 

**Refactoring tasks**
- [ ] Create a overall php file that contains all the written texts in one file as constants to make overall changes more easy

**Comment by Circleview** [comment]
Current result 

![image](https://cloud.githubusercontent.com/assets/6303048/18413543/2d0e983a-77ab-11e6-8ba5-b6fa673ebd59.png)

**Comment by Circleview** [comment]
![image](https://cloud.githubusercontent.com/assets/6303048/18413754/e02ba654-77b2-11e6-87c1-6c08490197c0.png)

**Comment by Circleview** [comment]
- [ ] Show the specific date for watering events that lay longer then one week in the past from #82 
- [ ] Show the specific day for watering days that lay one week in the past from #81 
- [ ] If the measure of the moisture drops it should not increase again to avoid false alarm. Sure the moisture should increase after a watering event. Maybe we can use thresholds for increased moisture from #80 
The idea here is that we later want to announce somewhere that the moisture dropped below a specific value and I want to avoid that the value was reset to a point where you cannot perform a watering action when you actually look at the message that told you to water the plant.

**Comment by Circleview** [comment]
Threshold like in #80 need to be increased.
